In [1]:
#Classifier takes integers and regressor takes floats
#THAT SAID THIS TELECOM NONSENSE IS MADE TO TEST CLASSIFICATION.
#TO REPEAT, CLASSIFICATION.
#USE PD GET DUMMIES INSTEAD OF LABEL ENCODER
#SCRATCH THAT!!! USE LABEL ENCODER AND LINEAR REGRESSION. MAKE ALL COLUMNS BINARY

import pandas as pd
#import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVC
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB

In [7]:
path = "resources/telecom_cleaned.csv"
df = pd.read_csv(path)
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Male,0,Yes,Yes,72,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.10,1734.65
1,Female,0,No,No,44,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),88.15,3973.20
2,Female,1,Yes,No,38,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.95,2869.85
3,Male,0,No,No,4,Yes,No,DSL,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,55.90,238.50
4,Male,0,No,No,2,Yes,No,DSL,Yes,No,Yes,No,No,No,Month-to-month,No,Electronic check,53.45,119.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5971,Male,0,Yes,No,1,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,95.00,95.00
5972,Female,0,Yes,Yes,23,Yes,Yes,DSL,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),91.10,2198.30
5973,Male,0,Yes,Yes,12,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Electronic check,21.15,306.05
5974,Male,1,No,No,12,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.45,1200.15
5975,Male,0,No,No,26,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),19.80,457.30

In [8]:
#inverse_transform(y) <-- How to turn labels back
#If gender is automatically binary. We don't need two columns.
label = LabelEncoder()

df = pd.get_dummies(df)

#for info in infos:
    #df[f"{info}"] = pd.get_dummies(df, columns = [f"{info}"])
    #df[f"{info}"] = label.fit_transform(df[f"{info}"])
    #df["gender"].value_counts()

In [9]:
df

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,72,24.10,1734.65,0,1,0,1,0,1,...,0,0,0,1,1,0,0,1,0,0
1,0,44,88.15,3973.20,1,0,1,0,1,0,...,0,1,0,0,0,1,0,1,0,0
2,1,38,74.95,2869.85,1,0,0,1,1,0,...,0,1,0,0,0,1,1,0,0,0
3,0,4,55.90,238.50,0,1,1,0,1,0,...,1,1,0,0,0,1,0,0,1,0
4,0,2,53.45,119.50,0,1,1,0,1,0,...,0,1,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5971,0,1,95.00,95.00,0,1,0,1,1,0,...,1,1,0,0,0,1,0,0,1,0
5972,0,23,91.10,2198.30,1,0,0,1,0,1,...,1,0,0,1,0,1,0,1,0,0
5973,0,12,21.15,306.05,0,1,0,1,0,1,...,0,1,0,0,0,1,0,0,1,0
5974,1,12,99.45,1200.15,0,1,1,0,1,0,...,1,1,0,0,0,1,0,0,1,0
5975,0,26,19.80,457.30,0,1,1,0,1,0,...,0,0,1,0,1,0,0,1,0,0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5976 entries, 0 to 5975
Data columns (total 45 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   SeniorCitizen                            5976 non-null   int64
 1   tenure                                   5976 non-null   int64
 2   MonthlyCharges                           5976 non-null   float64
 3   TotalCharges                             5976 non-null   float64
 4   gender_Female                            5976 non-null   uint8
 5   gender_Male                              5976 non-null   uint8
 6   Partner_No                               5976 non-null   uint8
 7   Partner_Yes                              5976 non-null   uint8
 8   Dependents_No                            5976 non-null   uint8
 9   Dependents_Yes                           5976 non-null   uint8
 10  PhoneService_No                          5976 non-null   uint8
 11  PhoneService_Yes                         5976 non-null   uint8
 12  MultipleLines_No                         5976 non-null   uint8
 13  MultipleLines_No phone service           5976 non-null   uint8
 14  MultipleLines_Yes                        5976 non-null   uint8
 15  InternetService_DSL                      5976 non-null   uint8
 16  InternetService_Fiber optic              5976 non-null   uint8
 17  InternetService_No                       5976 non-null   uint8
 18  OnlineSecurity_No                        5976 non-null   uint8
 19  OnlineSecurity_No internet service       5976 non-null   uint8
 20  OnlineSecurity_Yes                       5976 non-null   uint8
 21  OnlineBackup_No                          5976 non-null   uint8
 22  OnlineBackup_No internet service         5976 non-null   uint8
 23  OnlineBackup_Yes                         5976 non-null   uint8
 24  DeviceProtection_No                      5976 non-null   uint8
 25  DeviceProtection_No internet service     5976 non-null   uint8
 26  DeviceProtection_Yes                     5976 non-null   uint8
 27  TechSupport_No                           5976 non-null   uint8
 28  TechSupport_No internet service          5976 non-null   uint8
 29  TechSupport_Yes                          5976 non-null   uint8
 30  StreamingTV_No                           5976 non-null   uint8
 31  StreamingTV_No internet service          5976 non-null   uint8
 32  StreamingTV_Yes                          5976 non-null   uint8
 33  StreamingMovies_No                       5976 non-null   uint8
 34  StreamingMovies_No internet service      5976 non-null   uint8
 35  StreamingMovies_Yes                      5976 non-null   uint8
 36  Contract_Month-to-month                  5976 non-null   uint8
 37  Contract_One year                        5976 non-null   uint8
 38  Contract_Two year                        5976 non-null   uint8
 39  PaperlessBilling_No                      5976 non-null   uint8
 40  PaperlessBilling_Yes                     5976 non-null   uint8
 41  PaymentMethod_Bank transfer (automatic)  5976 non-null   uint8
 42  PaymentMethod_Credit card (automatic)    5976 non-null   uint8
 43  PaymentMethod_Electronic check           5976 non-null   uint8
 44  PaymentMethod_Mailed check               5976 non-null   uint8
dtypes: float64(2), int64(2), uint8(41)
memory usage: 426.1 KB

In [11]:
X = df.drop(['MonthlyCharges', 'tenure'], axis=1)
y = df["MonthlyCharges"]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state=42)

In [13]:
sc =  StandardScaler()
X_scaler = sc.fit(X_train)
X_train = X_scaler.transform(X_train)
X_test = X_scaler.transform(X_test)

X_train

array([[-0.4472136 , -0.8414458 , -0.98934723, ..., -0.53969485,
         1.41848397, -0.54899338],
       [-0.4472136 ,  1.78477182, -0.98934723, ..., -0.53969485,
        -0.70497801, -0.54899338],
       [-0.4472136 ,  1.78025691,  1.01076747, ...,  1.85289892,
        -0.70497801, -0.54899338],
       ...,
       [-0.4472136 ,  1.00988636, -0.98934723, ..., -0.53969485,
        -0.70497801,  1.8215156 ],
       [-0.4472136 ,  0.93756052, -0.98934723, ..., -0.53969485,
        -0.70497801,  1.8215156 ],
       [-0.4472136 ,  1.81295185,  1.01076747, ..., -0.53969485,
        -0.70497801, -0.54899338]])

# Linear Regression

In [14]:
line = LinearRegression()
line.fit(X_train, y_train)


pred_line = line.predict(X_train)
mse = mean_squared_error(y_train, pred_line)
r2 = r2_score(y_train, pred_line)

print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2 ): {r2}")

Mean Squared Error (MSE): 1.058181069747864
R-squared (R2 ): 0.9988411280237882

In [15]:
line.score(X_test, y_test)

0.9988688966220702