In [1]:
#Classifier takes integers and regressor takes floats
#THAT SAID THIS TELECOM NONSENSE IS MADE TO TEST CLASSIFICATION.
#TO REPEAT, CLASSIFICATION.
#USE PD GET DUMMIES INSTEAD OF LABEL ENCODER

import pandas as pd
#import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVC
from sklearn.svm import SVR
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB

In [2]:
path = "resources/telecom_users.csv"
df = pd.read_csv(path)
df

,Unnamed: 0,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1869,7010-BRBUU,Male,0,Yes,Yes,72,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.10,1734.65,No
1,4528,9688-YGXVR,Female,0,No,No,44,Yes,No,Fiber optic,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),88.15,3973.2,No
2,6344,9286-DOJGF,Female,1,Yes,No,38,Yes,Yes,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.95,2869.85,Yes
3,6739,6994-KERXL,Male,0,No,No,4,Yes,No,DSL,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,55.90,238.5,No
4,432,2181-UAESM,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,Month-to-month,No,Electronic check,53.45,119.5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,3772,0684-AOSIH,Male,0,Yes,No,1,Yes,No,Fiber optic,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,95.00,95,Yes
5982,5191,5982-PSMKW,Female,0,Yes,Yes,23,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),91.10,2198.3,No
5983,5226,8044-BGWPI,Male,0,Yes,Yes,12,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Electronic check,21.15,306.05,No
5984,5390,7450-NWRTR,Male,1,No,No,12,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.45,1200.15,Yes
5985,860,4795-UXVCJ,Male,0,No,No,26,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),19.80,457.3,No

In [3]:
#Turn unrecognized spaces into NaNs
df['TotalCharges'].replace(' ', np.nan, inplace=True)
df['MonthlyCharges'].replace(' ', np.nan, inplace=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        5986 non-null   int64
 1   customerID        5986 non-null   object
 2   gender            5986 non-null   object
 3   SeniorCitizen     5986 non-null   int64
 4   Partner           5986 non-null   object
 5   Dependents        5986 non-null   object
 6   tenure            5986 non-null   int64
 7   PhoneService      5986 non-null   object
 8   MultipleLines     5986 non-null   object
 9   InternetService   5986 non-null   object
 10  OnlineSecurity    5986 non-null   object
 11  OnlineBackup      5986 non-null   object
 12  DeviceProtection  5986 non-null   object
 13  TechSupport       5986 non-null   object
 14  StreamingTV       5986 non-null   object
 15  StreamingMovies   5986 non-null   object
 16  Contract          5986 non-null   object
 17  PaperlessBilling  5986 non-null   object
 18  PaymentMethod     5986 non-null   object
 19  MonthlyCharges    5986 non-null   float64
 20  TotalCharges      5976 non-null   object
 21  Churn             5986 non-null   object
dtypes: float64(1), int64(3), object(18)
memory usage: 1.0+ MB

In [5]:
#Find Strings
df[pd.to_numeric(df.TotalCharges, errors='coerce').isnull()]
#It's a space. Erase the spaces.

#Find Numbers
df[pd.to_numeric(df.TotalCharges, errors='coerce').notnull()]

,Unnamed: 0,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1869,7010-BRBUU,Male,0,Yes,Yes,72,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.10,1734.65,No
1,4528,9688-YGXVR,Female,0,No,No,44,Yes,No,Fiber optic,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),88.15,3973.2,No
2,6344,9286-DOJGF,Female,1,Yes,No,38,Yes,Yes,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.95,2869.85,Yes
3,6739,6994-KERXL,Male,0,No,No,4,Yes,No,DSL,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,55.90,238.5,No
4,432,2181-UAESM,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,Month-to-month,No,Electronic check,53.45,119.5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,3772,0684-AOSIH,Male,0,Yes,No,1,Yes,No,Fiber optic,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,95.00,95,Yes
5982,5191,5982-PSMKW,Female,0,Yes,Yes,23,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),91.10,2198.3,No
5983,5226,8044-BGWPI,Male,0,Yes,Yes,12,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Electronic check,21.15,306.05,No
5984,5390,7450-NWRTR,Male,1,No,No,12,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.45,1200.15,Yes
5985,860,4795-UXVCJ,Male,0,No,No,26,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),19.80,457.3,No

In [6]:
#Drop NaNs
df.dropna(subset=['TotalCharges'], inplace=True)
df

,Unnamed: 0,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1869,7010-BRBUU,Male,0,Yes,Yes,72,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.10,1734.65,No
1,4528,9688-YGXVR,Female,0,No,No,44,Yes,No,Fiber optic,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),88.15,3973.2,No
2,6344,9286-DOJGF,Female,1,Yes,No,38,Yes,Yes,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.95,2869.85,Yes
3,6739,6994-KERXL,Male,0,No,No,4,Yes,No,DSL,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,55.90,238.5,No
4,432,2181-UAESM,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,Month-to-month,No,Electronic check,53.45,119.5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,3772,0684-AOSIH,Male,0,Yes,No,1,Yes,No,Fiber optic,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,95.00,95,Yes
5982,5191,5982-PSMKW,Female,0,Yes,Yes,23,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),91.10,2198.3,No
5983,5226,8044-BGWPI,Male,0,Yes,Yes,12,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Electronic check,21.15,306.05,No
5984,5390,7450-NWRTR,Male,1,No,No,12,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.45,1200.15,Yes
5985,860,4795-UXVCJ,Male,0,No,No,26,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),19.80,457.3,No

In [7]:
#NaNs are gone
df[pd.to_numeric(df.TotalCharges, errors='coerce').isnull()]

Empty DataFrame
Columns: [Unnamed: 0, customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 22 columns]

In [8]:
df["TotalCharges"] = df["TotalCharges"].astype(float)
df.to_csv("resources/telecom_cleaned.csv", index=False)

In [9]:
print(df["TotalCharges"].max())
print(df["TotalCharges"].min())

print(df["MonthlyCharges"].max())
print(df["MonthlyCharges"].min())

8684.8
18.8
118.75
18.25

In [10]:
#inverse_transform(y) <-- How to turn labels back
label = LabelEncoder()


#df["MonthlyCharges"] = label.fit_transform(df["MonthlyCharges"])
#df["TotalCharges"] = df["TotalCharges"].round(1)
#df["MonthlyCharges"] = df["MonthlyCharges"].round(1)

infos = ["gender", "SeniorCitizen", "Partner", "Dependents", "tenure", "PhoneService", 
        "MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup", "DeviceProtection",
        "TechSupport", "StreamingTV", "StreamingMovies", "Contract", "PaperlessBilling", "PaymentMethod", 
         "TotalCharges"]


for info in infos:
    df[f"{info}"] = pd.get_dummies(df, columns = [f"{info}"])
    #df[f"{info}"] = dummies.fit_transform(df[f"{info}"])
    #df["gender"].value_counts()

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5976 entries, 0 to 5985
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        5976 non-null   int64
 1   customerID        5976 non-null   object
 2   gender            5976 non-null   object
 3   SeniorCitizen     5976 non-null   object
 4   Partner           5976 non-null   object
 5   Dependents        5976 non-null   object
 6   tenure            5976 non-null   object
 7   PhoneService      5976 non-null   object
 8   MultipleLines     5976 non-null   object
 9   InternetService   5976 non-null   object
 10  OnlineSecurity    5976 non-null   object
 11  OnlineBackup      5976 non-null   object
 12  DeviceProtection  5976 non-null   object
 13  TechSupport       5976 non-null   object
 14  StreamingTV       5976 non-null   object
 15  StreamingMovies   5976 non-null   object
 16  Contract          5976 non-null   object
 17  PaperlessBilling  5976 non-null   object
 18  PaymentMethod     5976 non-null   object
 19  MonthlyCharges    5976 non-null   float64
 20  TotalCharges      5976 non-null   object
 21  Churn             5976 non-null   object
dtypes: float64(1), int64(1), object(20)
memory usage: 1.0+ MB

In [12]:
#Transforming from object to category
df['gender']=df['gender'].astype('category')
df['SeniorCitizen']=df['SeniorCitizen'].astype('category')
df['Partner']=df['Partner'].astype('category')
df['Dependents']=df['Dependents'].astype('category')
df['PhoneService']=df['PhoneService'].astype('category')
df['MultipleLines']=df['MultipleLines'].astype('category')
df['InternetService']=df['InternetService'].astype('category')
df['OnlineSecurity']=df['OnlineSecurity'].astype('category')
df['OnlineBackup']=df['OnlineBackup'].astype('category')
df['DeviceProtection']=df['DeviceProtection'].astype('category')
df['TechSupport']=df['TechSupport'].astype('category')
df['StreamingTV']=df['StreamingTV'].astype('category')
df['StreamingMovies']=df['StreamingMovies'].astype('category')
df['Contract']=df['Contract'].astype('category')
df['PaperlessBilling']=df['PaperlessBilling'].astype('category')
df['PaymentMethod']=df['PaymentMethod'].astype('category')
df['Churn']=df['Churn'].astype('category')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5976 entries, 0 to 5985
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        5976 non-null   int64
 1   customerID        5976 non-null   object
 2   gender            5976 non-null   category
 3   SeniorCitizen     5976 non-null   category
 4   Partner           5976 non-null   category
 5   Dependents        5976 non-null   category
 6   tenure            5976 non-null   object
 7   PhoneService      5976 non-null   category
 8   MultipleLines     5976 non-null   category
 9   InternetService   5976 non-null   category
 10  OnlineSecurity    5976 non-null   category
 11  OnlineBackup      5976 non-null   category
 12  DeviceProtection  5976 non-null   category
 13  TechSupport       5976 non-null   category
 14  StreamingTV       5976 non-null   category
 15  StreamingMovies   5976 non-null   category
 16  Contract          5976 non-null   category
 17  PaperlessBilling  5976 non-null   category
 18  PaymentMethod     5976 non-null   category
 19  MonthlyCharges    5976 non-null   float64
 20  TotalCharges      5976 non-null   object
 21  Churn             5976 non-null   category
dtypes: category(17), float64(1), int64(1), object(3)
memory usage: 3.7+ MB