In [154]:
#Classifier takes integers and regressor takes floats
#THAT SAID THIS TELECOM NONSENSE IS MADE TO TEST CLASSIFICATION.
#TO REPEAT, CLASSIFICATION.
#USE PD GET DUMMIES INSTEAD OF LABEL ENCODER

import pandas as pd
#import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVC
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB

ImportError: cannot import name 'regression_report'

In [132]:
path = "resources/telecom_users.csv"
df = pd.read_csv(path)
df

,Unnamed: 0,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1869,7010-BRBUU,Male,0,Yes,Yes,72,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.10,1734.65,No
1,4528,9688-YGXVR,Female,0,No,No,44,Yes,No,Fiber optic,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),88.15,3973.2,No
2,6344,9286-DOJGF,Female,1,Yes,No,38,Yes,Yes,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.95,2869.85,Yes
3,6739,6994-KERXL,Male,0,No,No,4,Yes,No,DSL,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,55.90,238.5,No
4,432,2181-UAESM,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,Month-to-month,No,Electronic check,53.45,119.5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,3772,0684-AOSIH,Male,0,Yes,No,1,Yes,No,Fiber optic,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,95.00,95,Yes
5982,5191,5982-PSMKW,Female,0,Yes,Yes,23,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),91.10,2198.3,No
5983,5226,8044-BGWPI,Male,0,Yes,Yes,12,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Electronic check,21.15,306.05,No
5984,5390,7450-NWRTR,Male,1,No,No,12,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.45,1200.15,Yes
5985,860,4795-UXVCJ,Male,0,No,No,26,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),19.80,457.3,No

In [133]:
#Turn unrecognized spaces into NaNs
df['TotalCharges'].replace(' ', np.nan, inplace=True)
df['MonthlyCharges'].replace(' ', np.nan, inplace=True)

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        5986 non-null   int64
 1   customerID        5986 non-null   object
 2   gender            5986 non-null   object
 3   SeniorCitizen     5986 non-null   int64
 4   Partner           5986 non-null   object
 5   Dependents        5986 non-null   object
 6   tenure            5986 non-null   int64
 7   PhoneService      5986 non-null   object
 8   MultipleLines     5986 non-null   object
 9   InternetService   5986 non-null   object
 10  OnlineSecurity    5986 non-null   object
 11  OnlineBackup      5986 non-null   object
 12  DeviceProtection  5986 non-null   object
 13  TechSupport       5986 non-null   object
 14  StreamingTV       5986 non-null   object
 15  StreamingMovies   5986 non-null   object
 16  Contract          5986 non-null   object
 17  PaperlessBilling  5986 non-null   object
 18  PaymentMethod     5986 non-null   object
 19  MonthlyCharges    5986 non-null   float64
 20  TotalCharges      5976 non-null   object
 21  Churn             5986 non-null   object
dtypes: float64(1), int64(3), object(18)
memory usage: 1.0+ MB

In [135]:
#Find Strings
df[pd.to_numeric(df.TotalCharges, errors='coerce').isnull()]
#It's a space. Erase the spaces.

#Find Numbers
df[pd.to_numeric(df.TotalCharges, errors='coerce').notnull()]

,Unnamed: 0,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1869,7010-BRBUU,Male,0,Yes,Yes,72,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.10,1734.65,No
1,4528,9688-YGXVR,Female,0,No,No,44,Yes,No,Fiber optic,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),88.15,3973.2,No
2,6344,9286-DOJGF,Female,1,Yes,No,38,Yes,Yes,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.95,2869.85,Yes
3,6739,6994-KERXL,Male,0,No,No,4,Yes,No,DSL,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,55.90,238.5,No
4,432,2181-UAESM,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,Month-to-month,No,Electronic check,53.45,119.5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,3772,0684-AOSIH,Male,0,Yes,No,1,Yes,No,Fiber optic,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,95.00,95,Yes
5982,5191,5982-PSMKW,Female,0,Yes,Yes,23,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),91.10,2198.3,No
5983,5226,8044-BGWPI,Male,0,Yes,Yes,12,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Electronic check,21.15,306.05,No
5984,5390,7450-NWRTR,Male,1,No,No,12,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.45,1200.15,Yes
5985,860,4795-UXVCJ,Male,0,No,No,26,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),19.80,457.3,No

In [136]:
#Drop NaNs
df.dropna(subset=['TotalCharges'], inplace=True)
df

,Unnamed: 0,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1869,7010-BRBUU,Male,0,Yes,Yes,72,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.10,1734.65,No
1,4528,9688-YGXVR,Female,0,No,No,44,Yes,No,Fiber optic,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),88.15,3973.2,No
2,6344,9286-DOJGF,Female,1,Yes,No,38,Yes,Yes,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.95,2869.85,Yes
3,6739,6994-KERXL,Male,0,No,No,4,Yes,No,DSL,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,55.90,238.5,No
4,432,2181-UAESM,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,Month-to-month,No,Electronic check,53.45,119.5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,3772,0684-AOSIH,Male,0,Yes,No,1,Yes,No,Fiber optic,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,95.00,95,Yes
5982,5191,5982-PSMKW,Female,0,Yes,Yes,23,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),91.10,2198.3,No
5983,5226,8044-BGWPI,Male,0,Yes,Yes,12,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Electronic check,21.15,306.05,No
5984,5390,7450-NWRTR,Male,1,No,No,12,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.45,1200.15,Yes
5985,860,4795-UXVCJ,Male,0,No,No,26,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),19.80,457.3,No

In [137]:
#NaNs are gone
df[pd.to_numeric(df.TotalCharges, errors='coerce').isnull()]

Empty DataFrame
Columns: [Unnamed: 0, customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 22 columns]

In [138]:
df["TotalCharges"] = df["TotalCharges"].astype(float)
df.to_csv("resources/telecom_cleaned.csv", index=False)

In [139]:
print(df["TotalCharges"].max())
print(df["TotalCharges"].min())

print(df["MonthlyCharges"].max())
print(df["MonthlyCharges"].min())

8684.8
18.8
118.75
18.25

In [141]:
#inverse_transform(y) <-- How to turn labels back
label = LabelEncoder()


#df["MonthlyCharges"] = label.fit_transform(df["MonthlyCharges"])
#df["TotalCharges"] = df["TotalCharges"].round(1)
#df["MonthlyCharges"] = df["MonthlyCharges"].round(1)

infos = ["gender", "SeniorCitizen", "Partner", "Dependents", "tenure", "PhoneService", 
        "MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup", "DeviceProtection",
        "TechSupport", "StreamingTV", "StreamingMovies", "Contract", "PaperlessBilling", "PaymentMethod", 
         "TotalCharges"]


for info in infos:
    df[f"{info}"] = pd.get_dummies(df, columns = [f"{info}"])
    #df[f"{info}"] = dummies.fit_transform(df[f"{info}"])
    #df["gender"].value_counts()

In [142]:
data = df[["gender", "SeniorCitizen", "Partner", "Dependents", "PhoneService", 
           "MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup", "DeviceProtection",
          "TechSupport", "StreamingTV", "StreamingMovies", "Contract", "PaperlessBilling", "PaymentMethod",
          "TotalCharges"]]
data

,gender,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges
0,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869
1,4528,4528,4528,4528,4528,4528,4528,4528,4528,4528,4528,4528,4528,4528,4528,4528,4528
2,6344,6344,6344,6344,6344,6344,6344,6344,6344,6344,6344,6344,6344,6344,6344,6344,6344
3,6739,6739,6739,6739,6739,6739,6739,6739,6739,6739,6739,6739,6739,6739,6739,6739,6739
4,432,432,432,432,432,432,432,432,432,432,432,432,432,432,432,432,432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772
5982,5191,5191,5191,5191,5191,5191,5191,5191,5191,5191,5191,5191,5191,5191,5191,5191,5191
5983,5226,5226,5226,5226,5226,5226,5226,5226,5226,5226,5226,5226,5226,5226,5226,5226,5226
5984,5390,5390,5390,5390,5390,5390,5390,5390,5390,5390,5390,5390,5390,5390,5390,5390,5390
5985,860,860,860,860,860,860,860,860,860,860,860,860,860,860,860,860,860

In [143]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5976 entries, 0 to 5985
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            5976 non-null   object
 1   SeniorCitizen     5976 non-null   object
 2   Partner           5976 non-null   object
 3   Dependents        5976 non-null   object
 4   PhoneService      5976 non-null   object
 5   MultipleLines     5976 non-null   object
 6   InternetService   5976 non-null   object
 7   OnlineSecurity    5976 non-null   object
 8   OnlineBackup      5976 non-null   object
 9   DeviceProtection  5976 non-null   object
 10  TechSupport       5976 non-null   object
 11  StreamingTV       5976 non-null   object
 12  StreamingMovies   5976 non-null   object
 13  Contract          5976 non-null   object
 14  PaperlessBilling  5976 non-null   object
 15  PaymentMethod     5976 non-null   object
 16  TotalCharges      5976 non-null   object
dtypes: object(17)
memory usage: 840.4+ KB

In [144]:
X = data
y = df["MonthlyCharges"]

In [145]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [146]:
y_train

1782     98.65
3210     45.95
3041     81.00
5099     85.60
304     110.65
         ...
3777     95.40
5197    100.05
5232     67.85
5398     85.15
862      90.95
Name: MonthlyCharges, Length: 4482, dtype: float64

In [147]:
sc =  StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train

array([[-1.56821101, -1.56821101, -1.56821101, ..., -1.56821101,
        -1.56821101, -1.56821101],
       [-0.59295496, -0.59295496, -0.59295496, ..., -0.59295496,
        -0.59295496, -0.59295496],
       [ 1.23522197,  1.23522197,  1.23522197, ...,  1.23522197,
         1.23522197,  1.23522197],
       ...,
       [-0.77156432, -0.77156432, -0.77156432, ..., -0.77156432,
        -0.77156432, -0.77156432],
       [-1.33185945, -1.33185945, -1.33185945, ..., -1.33185945,
        -1.33185945, -1.33185945],
       [-0.9599605 , -0.9599605 , -0.9599605 , ..., -0.9599605 ,
        -0.9599605 , -0.9599605 ]])

In [148]:
#train_scores = []
#test_scores = []
#for k in range(1, 20, 2):
    #knn = KNeighborsClassifier(n_neighbors=k)
    #knn.fit(X_train, y_train)
    #train_score = knn.score(X_train, y_train)
    #test_score = knn.score(X_test, y_test)
    #train_scores.append(train_score)
    #test_scores.append(test_score)
    #print(f"k: {k}, Train/Test Score: {train_score:.3f}/{test_score:.3f}")
    
    
#plt.plot(range(1, 20, 2), train_scores, marker='o')
#plt.plot(range(1, 20, 2), test_scores, marker="x")
#plt.xlabel("k neighbors")
#plt.ylabel("Testing accuracy Score")
#plt.show()

In [156]:
rfc = RandomForestRegressor(n_estimators=200)
rfc.fit(X_train, y_train)
pred_rfc = rfc.predict(X_test)
print(pred_rfc)
print(y_train)

[47.055   38.062   83.99925 ... 35.06025 64.9055  75.9275 ]
1782     98.65
3210     45.95
3041     81.00
5099     85.60
304     110.65
         ...
3777     95.40
5197    100.05
5232     67.85
5398     85.15
862      90.95
Name: MonthlyCharges, Length: 4482, dtype: float64

In [150]:
print(f"Training Data Score: {rfc.score(X_train, y_train)}")
print(f"Testing Data Score: {rfc.score(X_test, y_test)}")

Training Data Score: 0.8084966388013543
Testing Data Score: -0.5795053727839787

In [152]:
print(regression_report(y_test, pred_rfc))
print(confusion_matrix(y_test, pred_rfc))

NameError: name 'regression_report' is not defined